# This file describes the config settings available in the workflow controller configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # Configure artifact repository
  # using minio in this example
  artifactRepository: |
    s3:
      bucket: my-bucket
      endpoint: argo-artifacts.argo.svc.cluster.local:9000
      insecure: true
      # References to kubernetes secrets holding credentials
      accessKeySecret:
        name: argo-artifacts
        key: accesskey
      secretKeySecret:
        name: argo-artifacts
        key: secretkey
